//! Generate the hardware reference snippets for the mdBook from canonical
//! source: the board registry, transport kinds, the tool catalog, and the
//! release target matrix. The registry is the single source of truth; the docs
//! render whatever it carries so a board add, transport rename, tool rename, or
//! target change reflows the rendered tables on the next build with no hand
//! edit.
//!
//! Outputs (gitignored, derived — `{{#include}}`d at build time):
//!   docs/book/src/_snippets/hardware-boards.md
//!   docs/book/src/_snippets/hardware-transports.md
//!   docs/book/src/_snippets/hardware-tools-base.md
//!   docs/book/src/_snippets/hardware-tools-aardvark.md
//!   docs/book/src/_snippets/hardware-release-targets.md

use anyhow::Result;
use std::fmt::Write as _;
use std::path::Path;

use zeroclaw_hardware::catalog::{AARDVARK_TOOLS, BASE_TOOLS};
use zeroclaw_hardware::registry::known_boards;
use zeroclaw_hardware::transport::TransportKind;

const SNIPPET_DIR: &str = "docs/book/src/_snippets";

const HEADER: &str = "<!--\n  GENERATED by `cargo xtask mdbook` from canonical hardware source\n  (registry.rs, transport.rs, catalog.rs, release workflow). Derived +\n  gitignored: do not edit, do not commit. Regenerated on every docs build.\n-->\n\n";

/// Release targets that ship a prebuilt binary. Mirrors the `target:` matrix in
/// `.github/workflows/release-stable-manual.yml`; the workflow is the canonical
/// source. Parsed from the workflow at generation time so the two cannot drift.
const RELEASE_WORKFLOW: &str = ".github/workflows/release-stable-manual.yml";

/// The bootstrap installer. Its low-memory build heuristic
/// (`apply_low_mem_lto_default`) is the canonical source for the RAM threshold
/// below which the source build switches to thin LTO. Parsed at generation time
/// so the doc number cannot drift from the script.
const INSTALL_SH: &str = "install.sh";

pub fn run(root: &Path) -> Result<()> {
    let dir = root.join(SNIPPET_DIR);
    std::fs::create_dir_all(&dir)?;

    std::fs::write(dir.join("hardware-boards.md"), render_boards())?;
    std::fs::write(dir.join("hardware-transports.md"), render_transports())?;
    std::fs::write(
        dir.join("hardware-tools-base.md"),
        render_tool_list(BASE_TOOLS),
    )?;
    std::fs::write(
        dir.join("hardware-tools-aardvark.md"),
        render_tool_list(AARDVARK_TOOLS),
    )?;
    std::fs::write(
        dir.join("hardware-release-targets.md"),
        render_release_targets(root)?,
    )?;
    std::fs::write(dir.join("hardware-pi-targets.md"), render_pi_targets(root)?)?;
    std::fs::write(dir.join("hardware-lowmem-lto.md"), render_lowmem_lto(root)?)?;

    eprintln!("==> Generated hardware reference snippets from registry + catalog");
    Ok(())
}

fn render_boards() -> String {
    let mut out = String::from(HEADER);
    out.push_str("| Board | Architecture | USB VID:PID |\n|---|---|---|\n");
    for b in known_boards() {
        let arch = b.architecture.unwrap_or("(unspecified)");
        let _ = writeln!(
            out,
            "| `{}` | {} | `{:#06x}`:`{:#06x}` |",
            b.name, arch, b.vid, b.pid
        );
    }
    out
}

fn render_transports() -> String {
    let mut out = String::from(HEADER);
    out.push_str("| Transport | Description |\n|---|---|\n");
    for (kind, desc) in [
        (
            TransportKind::Serial,
            "Newline-delimited JSON over USB CDC serial",
        ),
        (TransportKind::Swd, "SWD debug probe (probe-rs)"),
        (TransportKind::Uf2, "UF2 mass-storage firmware flashing"),
        (
            TransportKind::Native,
            "Direct Linux GPIO/I2C/SPI (rppal, sysfs)",
        ),
        (
            TransportKind::Aardvark,
            "Total Phase Aardvark USB adapter (I2C/SPI/GPIO)",
        ),
    ] {
        let _ = writeln!(out, "| `{kind}` | {desc} |");
    }
    out
}

fn render_tool_list(tools: &[&str]) -> String {
    let mut out = String::from(HEADER);
    for name in tools {
        let _ = writeln!(out, "- `{name}`");
    }
    out
}

fn render_lowmem_lto(root: &Path) -> Result<String> {
    let script = std::fs::read_to_string(root.join(INSTALL_SH)).map_err(|e| {
        anyhow::Error::msg(format!(
            "{INSTALL_SH} missing: {e}. It is the canonical source for the \
             low-memory build heuristic."
        ))
    })?;
    // Parse the threshold from `apply_low_mem_lto_default`:
    //   if [ "$mem_kb" -lt 12582912 ]; then
    let kib: u64 = script
        .lines()
        .find_map(|l| {
            let rest = l.trim().strip_prefix(r#"if [ "$mem_kb" -lt "#)?;
            rest.split_whitespace().next()?.parse::<u64>().ok()
        })
        .ok_or_else(|| {
            anyhow::Error::msg(format!(
                "could not parse the `$mem_kb -lt <KiB>` low-memory threshold from \
                 {INSTALL_SH}::apply_low_mem_lto_default"
            ))
        })?;
    let gib = kib / (1024 * 1024);
    let mut out = String::from(HEADER);
    let _ = writeln!(
        out,
        "When `install.sh` builds from source on Linux, it reads `MemTotal` from \
         `/proc/meminfo` and, on hosts with **under {gib} GiB** of RAM, exports \
         `CARGO_PROFILE_RELEASE_LTO=thin` before building. Fat LTO (the \
         `[profile.release]` default) can peak past 7 GB RSS during the \
         cross-crate type pass and OOM a low-RAM board; thin LTO trades a small \
         binary-size increase for a much lower build-time memory peak."
    );
    out.push('\n');
    out.push_str(
        "The switch only applies when you have not already pinned the variable. \
         Override either direction explicitly:\n\n",
    );
    out.push_str(
        "```sh\n# Force fat LTO even on a low-RAM host (smaller binary, higher build RAM)\nexport CARGO_PROFILE_RELEASE_LTO=fat\n\n# Force thin LTO on a high-RAM host (lower build RAM)\nexport CARGO_PROFILE_RELEASE_LTO=thin\n```\n",
    );
    Ok(out)
}

/// Parse the deduplicated, sorted `target:` matrix from the release workflow.
/// The workflow is the canonical source for which architectures ship a prebuilt
/// binary; the docs render whatever it carries so the two cannot drift.
fn release_targets(root: &Path) -> Result<Vec<String>> {
    let workflow = std::fs::read_to_string(root.join(RELEASE_WORKFLOW)).map_err(|e| {
        anyhow::Error::msg(format!(
            "release workflow missing at {RELEASE_WORKFLOW}: {e}. It is the canonical \
             source for the prebuilt-binary target matrix."
        ))
    })?;
    let mut targets: Vec<String> = workflow
        .lines()
        .filter_map(|l| l.trim().strip_prefix("target:"))
        .map(|t| t.trim().to_string())
        .collect();
    targets.sort_unstable();
    targets.dedup();
    if targets.is_empty() {
        anyhow::bail!("no `target:` entries parsed from {RELEASE_WORKFLOW}");
    }
    Ok(targets)
}

fn render_release_targets(root: &Path) -> Result<String> {
    let mut out = String::from(HEADER);
    for t in release_targets(root)? {
        let _ = writeln!(out, "- `{t}`");
    }
    Ok(out)
}

/// Render only the targets a Raspberry Pi can run: ARM Linux GNU/glibc release
/// targets (32- and 64-bit). Derived from the same workflow matrix as the full
/// list, filtered by triple rather than hand-listed, so a new ARM Linux release
/// target appears here automatically and a dropped one disappears.
fn render_pi_targets(root: &Path) -> Result<String> {
    let pi: Vec<String> = release_targets(root)?
        .into_iter()
        .filter(|t| {
            let arm = t.starts_with("aarch64-") || t.starts_with("armv7-") || t.starts_with("arm-");
            arm && t.contains("-linux-gnu")
        })
        .collect();
    if pi.is_empty() {
        anyhow::bail!(
            "no ARM Linux GNU release targets parsed from {RELEASE_WORKFLOW}; \
             the Raspberry Pi prebuilt-binary list would be empty"
        );
    }
    let mut out = String::from(HEADER);
    for t in pi {
        let bits = if t.starts_with("aarch64-") {
            "64-bit"
        } else {
            "32-bit"
        };
        let _ = writeln!(out, "- `{t}` ({bits})");
    }
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn lowmem_lto_snippet_parses_and_renders_threshold() {
        let root = crate::util::repo_root();
        let snippet = render_lowmem_lto(&root).expect("install.sh threshold must parse");
        // The current install.sh threshold is 12 GiB (12582912 KiB). If the
        // script changes the literal, this snippet follows; this guard only
        // ensures the parse still finds a GiB value and emits the override block.
        assert!(
            snippet.contains("GiB** of RAM"),
            "rendered low-mem snippet missing GiB threshold: {snippet}"
        );
        assert!(
            snippet.contains("CARGO_PROFILE_RELEASE_LTO=thin"),
            "rendered low-mem snippet missing the LTO override: {snippet}"
        );
    }

    #[test]
    fn pi_targets_are_arm_linux_gnu_only() {
        let root = crate::util::repo_root();
        let snippet = render_pi_targets(&root).expect("pi targets must render");
        // Must include the ARM Linux GNU targets and exclude every non-Pi target
        // (macOS, Android, Windows, x86, musl) so the Pi page never lists a
        // binary a Pi can't run.
        assert!(snippet.contains("aarch64-unknown-linux-gnu"));
        for excluded in [
            "apple-darwin",
            "linux-android",
            "pc-windows",
            "x86_64-",
            "-linux-musl",
        ] {
            assert!(
                !snippet.contains(excluded),
                "Pi target list leaked non-Pi target containing {excluded:?}: {snippet}"
            );
        }
    }
}
