//! Generate the zerocode keybinding snippets for the mdBook from the canonical
//! default keymap (`apps/zerocode/src/keymap/actions.rs`). The registry is the
//! single source of truth; the docs render whatever chords it carries so a
//! rebind never drifts the rendered tables.
//!
//! Outputs (gitignored, derived — `{{#include}}`d at build time):
//!   docs/book/src/_snippets/zerocode-pane-nav-keys.md
//!   docs/book/src/_snippets/zerocode-quickstart-pane-keys.md

use anyhow::Result;
use std::fmt::Write as _;
use std::path::Path;

use zerocode::keymap::{Chord, GlobalAction, QuickstartTabAction, RebindableActions};

const SNIPPET_DIR: &str = "docs/book/src/_snippets";

const HEADER: &str = "<!--\n  GENERATED by `cargo xtask mdbook` from the default keymap in\n  apps/zerocode/src/keymap/actions.rs. Derived + gitignored: do not edit,\n  do not commit. Regenerated on every docs build.\n-->\n\n";

pub fn run(root: &Path) -> Result<()> {
    let dir = root.join(SNIPPET_DIR);
    std::fs::write(
        dir.join("zerocode-pane-nav-keys.md"),
        render_table(pane_nav_rows()),
    )?;
    std::fs::write(
        dir.join("zerocode-quickstart-pane-keys.md"),
        render_table(quickstart_rows()),
    )?;
    eprintln!("==> Generated zerocode keybinding snippets from default keymap");
    Ok(())
}

fn render_chords(chords: &[Chord]) -> String {
    let mut seen: Vec<String> = Vec::new();
    for c in chords {
        let d = c.display();
        if !seen.contains(&d) {
            seen.push(d);
        }
    }
    seen.join(" / ")
}

fn quickstart_rows() -> Vec<(String, &'static str)> {
    QuickstartTabAction::all()
        .iter()
        .map(|a| (render_chords(&a.defaults()), a.human_label()))
        .collect()
}

fn pane_nav_rows() -> Vec<(String, &'static str)> {
    GlobalAction::all()
        .iter()
        .filter(|a| matches!(a, GlobalAction::PaneNavLeft | GlobalAction::PaneNavRight))
        .map(|a| (render_chords(&a.defaults()), a.human_label()))
        .collect()
}

fn render_table(rows: Vec<(String, &'static str)>) -> String {
    let mut out = String::from(HEADER);
    out.push_str("| Keys | Action |\n|---|---|\n");
    for (keys, label) in rows {
        let _ = writeln!(out, "| `{keys}` | {label} |");
    }
    out
}
