//! Docker tag matrix generator. Emits the canonical `[[tags]]` table the
//! docker-publish workflow consumes. `flags` carries the resolved cargo flag
//! string and is the authoritative build input; `features` is human-readable
//! only. Fully generated.

use super::spec::{self, Selection};
use std::path::Path;

/// A published image tag bound to a selection and the dockerfile that builds it.
struct TagSpec {
    stem: &'static str,
    selection: Selection,
    dockerfile: &'static str,
    /// Build platforms the docker-publish workflow targets for this tag. Only
    /// `Dockerfile` carries the cross-compilation logic that builds an arm64
    /// image without emulating the Rust build under QEMU; `Containerfile` is
    /// amd64-only until the same cross-build support lands there.
    platforms: &'static str,
}

const MULTI_ARCH: &str = "linux/amd64,linux/arm64";
const AMD64_ONLY: &str = "linux/amd64";

/// The canonical tag set. Each selection maps to a stem + the dockerfile that
/// realizes it. Driven by selections, not literal tag strings.
fn tag_specs() -> Vec<TagSpec> {
    vec![
        TagSpec {
            stem: "minimal",
            selection: Selection::Minimal,
            dockerfile: "Dockerfile",
            platforms: MULTI_ARCH,
        },
        TagSpec {
            stem: "default-features",
            selection: Selection::Full,
            dockerfile: "Dockerfile",
            platforms: MULTI_ARCH,
        },
        TagSpec {
            stem: "dist",
            selection: Selection::Dist,
            dockerfile: "Dockerfile",
            platforms: MULTI_ARCH,
        },
        TagSpec {
            stem: "all-features",
            selection: Selection::All,
            dockerfile: "Containerfile",
            platforms: AMD64_ONLY,
        },
    ]
}

/// Render the docker tag matrix TOML. `flags` is the authoritative build
/// input; `features` is human-readable only.
pub fn render(root: &Path) -> anyhow::Result<String> {
    let version = spec::resolve_version(root)?;
    let mut out = String::new();
    out.push_str("# Generated by `cargo generate installers` - do not edit.\n");
    out.push_str("# Canonical docker tag matrix. Regenerate after a version or\n");
    out.push_str("# feature change; CI fails on drift.\n");
    out.push_str(&format!("version = \"{version}\"\n\n"));
    for ts in tag_specs() {
        let features = spec::resolve_feature_list(root, &ts.selection)?.join(",");
        let flags = spec::resolve_flags(root, &ts.selection)?;
        out.push_str("[[tags]]\n");
        out.push_str(&format!("stem = \"{}\"\n", ts.stem));
        out.push_str(&format!("pinned_tag = \"{}-v{version}\"\n", ts.stem));
        out.push_str(&format!("floating_tag = \"{}\"\n", ts.stem));
        out.push_str(&format!("dockerfile = \"{}\"\n", ts.dockerfile));
        out.push_str(&format!("platforms = \"{}\"\n", ts.platforms));
        out.push_str(&format!("flags = \"{flags}\"\n"));
        out.push_str(&format!("features = \"{features}\"\n\n"));
    }
    while out.ends_with('\n') {
        out.pop();
    }
    out.push('\n');
    Ok(out)
}

/// Render-or-check: the matrix is a fully generated file (no hand-written glue),
/// so the renderer ignores prior content and emits the whole document.
pub fn render_file(root: &Path, _current: &str) -> anyhow::Result<String> {
    render(root)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    fn root() -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .unwrap()
            .to_path_buf()
    }

    #[test]
    fn matrix_is_valid_toml_with_pinned_and_floating() {
        let s = render(&root()).unwrap();
        let v: toml::Value = toml::from_str(&s).expect("valid TOML");
        let tags = v["tags"].as_array().unwrap();
        assert_eq!(tags.len(), tag_specs().len());
        let ver = v["version"].as_str().unwrap();
        let dist = tags
            .iter()
            .find(|t| t["stem"].as_str() == Some("dist"))
            .unwrap();
        assert_eq!(dist["pinned_tag"].as_str().unwrap(), format!("dist-v{ver}"));
        assert_eq!(dist["floating_tag"].as_str().unwrap(), "dist");
    }

    #[test]
    fn dockerfile_tags_are_multi_arch_containerfile_is_amd64_only() {
        let s = render(&root()).unwrap();
        let v: toml::Value = toml::from_str(&s).unwrap();
        for t in v["tags"].as_array().unwrap() {
            let platforms = t["platforms"].as_str().unwrap();
            match t["dockerfile"].as_str().unwrap() {
                "Dockerfile" => assert_eq!(platforms, "linux/amd64,linux/arm64"),
                "Containerfile" => assert_eq!(platforms, "linux/amd64"),
                other => panic!("unexpected dockerfile {other}"),
            }
        }
    }

    #[test]
    fn minimal_carries_no_default_flag_default_features_does_not() {
        let s = render(&root()).unwrap();
        let v: toml::Value = toml::from_str(&s).unwrap();
        let tags = v["tags"].as_array().unwrap();
        let flags = |stem: &str| {
            tags.iter()
                .find(|t| t["stem"].as_str() == Some(stem))
                .unwrap()["flags"]
                .as_str()
                .unwrap()
                .to_string()
        };
        assert_eq!(flags("minimal"), "--no-default-features");
        assert_eq!(flags("default-features"), "");
        assert!(flags("dist").starts_with("--no-default-features --features"));
    }

    #[test]
    fn dist_tag_ships_channels_all_tag_ships_heavyweight() {
        let s = render(&root()).unwrap();
        let v: toml::Value = toml::from_str(&s).unwrap();
        let tags = v["tags"].as_array().unwrap();
        let dist = tags
            .iter()
            .find(|t| t["stem"].as_str() == Some("dist"))
            .unwrap();
        let all = tags
            .iter()
            .find(|t| t["stem"].as_str() == Some("all-features"))
            .unwrap();
        assert!(
            dist["features"]
                .as_str()
                .unwrap()
                .contains("channel-discord")
        );
        assert!(!dist["features"].as_str().unwrap().contains("hardware"));
        assert!(all["features"].as_str().unwrap().contains("hardware"));
    }
}
