name: Validate PR title

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

permissions:
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Run validator unit tests
        run: ./scripts/check-pr-title.test.sh
      - name: Check PR title
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: ./scripts/check-pr-title.sh "$PR_TITLE"
